// @ts-check

import fs from "fs/promises";

async function main() {
	const scripts = (await fs.readdir("src")).filter((e) => e.endsWith(".js"));

	await fs.writeFile(
		"exports.js",
		`// This file is generated by ./build.js\r\r${scripts
			.map((e) => `export * from "./src/${e}";`)
			.join("\r")}\r`
	);

	process.exit(0);
}

main();
